### ISSUE TITLE
AI package-ben használni kívánt függvények

### ISSUE THREAD

**Issue by olahkoo** [AdamBelakovics/catan-imsc-project#6]
- ai package-ben AI, illetve Material osztály nem létezik
- controller packageben megvalósítatlan függvények: 
	- ArrayList\<Vertex> getNodes()
	- HashMap\<DevCard, Integer> getPlayedDevelopmentCards(int playerID) // egy adott játékos kijátszott fejlesztés kártyái darabszámmal; nem kell feltétlen DevCard-ként átadni, akár String-gel is lehet, a lényeg hogy megkapjam az adott játékos mennyit játszott ki
	- ArrayList\<Vertex> getVillages(int playerID) // ez lehet akár ai osztályban is lehet, vagy más formában kapjuk meg a Village-eket és azokból határozzuk meg, hogy melyik csomópontokon van településünk
	- ArrayList\<Vertex> getNodes() // Edge objektum két végpontja
	- ArrayList\<Vertex> getNeighbours() // Vertex objektum szomszédos csúcspontjai
	- ArrayList\<Edge> getPlayerRoads(int playerID) // egy játékos összes útja, ami a pályán van, nem számít milyen sorrendben
	- boolean equals() függvények Edge-re (két végpont alapján), Node-ra

Természetesen ezeket a függvényeket ha másképp valósítjátok meg, de abból egy egyszerű saját függvénnyel elő tudom állítani amit fent leírtam, az is tökéletesen megfelel, a lényeg hogy valamilyen formában elérhetőek legyenek. Illetve az is teljesen mindegy, hogy a Player, vagy a Table osztályon keresztül érem el.

**Comment by AdamBelakovics** [comment]
# Additions

# in class Table:

ArrayList<Vertex> getNodes() returns a List of all Vertexes MÉG ÜRES!!!
ArrayList<Edge> getEdges() returns the List of all Edges
IteratorHex hexIterator() returns Iterator for Hexes. The next() method returns reference for current Hex.

# in class Player

ArrayList<DevCard> getPlayedDevelopmentCards() MÉG ÜRES!!! 

# in class Vertex

Settlement getSettlement() returns the Settlement contained by this Vertex  
ArrayList<Vertex> getNeighbours() returs List of neighboring Vertexes MÉG ÜRES!!!
boolean equals() 

# in class Edge

Road getRoad() returns the Road contained by this Edge
ArrayList<Vertex> getEnds() returns the Vertexes which the Edge connects
boolean equals() 

Remélem így megfelel. A függvények nagy része nincs megvalósítva, viszont arra figyeltem, hogy ne adjak vissza sehol null reference-t szóval valami üres, de használható dolgot kaptok.

**Comment by AdamBelakovics** [comment]
Ha minden rendben kérlek zárd le az issuet

**Comment by matesebi** [comment]
a függvények egy része package láthatóságú, így nem érjük le őket

**Comment by AdamBelakovics** [comment]
Átírtam őket szóljatok ha még van.

**Comment by olahkoo** [comment]
ArrayList<Edge> getPlayerRoads(int playerID) // egy játékos összes útja, ami a pályán van, nem számít milyen sorrendben
Ez kellene még valamilyen formában, mivel most csak azt tudom megnézni, hogy egy Edge-en van e út, viszont azt nem tudom eldönteni, hogy kié az az út. Ha ArrayList<Road>  -ként kapom, az is jó, viszont akkor a Road-ból le kell tudnom kérni azt az Edge-et, amin van.

ArrayList<Vertex> getVillages(int playerID) // ez lehet akár ai osztályban is lehet, vagy más formában kapjuk meg a Village-eket és azokból határozzuk meg, hogy melyik csomópontokon van településünk
Ezzel ugyanaz a probléma, ahogy láttam a Vertex-től tudom elkérni, hogy van-e rajta település, viszont a településről nem tudom, hogy kié. Ha látnám, hogy kié a település, azzal már elő tudnám állítani magamnak ezt a listát. 

Többi minden megvan szerintem.
